import sqlglot
from sqlglot import exp
from typing import Optional, List, Set
import logging

logger = logging.getLogger(__name__)

# Dangerous SQL statement types to reject
DANGEROUS_STATEMENT_TYPES = {
    exp.Insert,
    exp.Update,
    exp.Delete,
    exp.Drop,
    exp.Command,
}

# Keywords that indicate dangerous operations
DANGEROUS_KEYWORDS = {
    'INSERT', 'UPDATE', 'DELETE', 'DROP', 'ALTER', 'TRUNCATE', 
    'CREATE', 'GRANT', 'REVOKE', 'MERGE', 'EXEC', 'EXECUTE', 'CALL'
}

class SQLValidationError(Exception):
    pass

class SQLValidator:
    def __init__(self, allowed_tables: Optional[Set[str]] = None, allowed_columns: Optional[Set[str]] = None):
        self.allowed_tables = allowed_tables
        self.allowed_columns = allowed_columns

    def validate_sql(self, sql: str) -> tuple[bool, Optional[str]]:
        """
        Validate SQL query for safety.
        
        Returns:
            (is_valid, error_message)
        """
        try:
            # Check for multiple statements
            if ';' in sql.strip():
                # Split by semicolon and check if there are multiple non-empty statements
                statements = [s.strip() for s in sql.split(';') if s.strip()]
                if len(statements) > 1:
                    return False, "Multiple SQL statements are not allowed"
            
            # Parse SQL using sqlglot
            parsed = sqlglot.parse_one(sql, dialect='postgres')
            
            # Check statement type
            if not isinstance(parsed, exp.Select):
                return False, "Only SELECT statements are allowed"
            
            # Check for dangerous keywords in the raw SQL
            sql_upper = sql.upper()
            for keyword in DANGEROUS_KEYWORDS:
                if keyword in sql_upper:
                    return False, f"Dangerous keyword '{keyword}' detected"
            
            # Extract tables used in the query
            tables = self._extract_tables(parsed)
            
            # Validate tables if allowed_tables is set
            if self.allowed_tables:
                for table in tables:
                    if table not in self.allowed_tables:
                        return False, f"Table '{table}' is not allowed"
            
            # Extract columns used in the query
            columns = self._extract_columns(parsed)
            
            # Validate columns if allowed_columns is set
            if self.allowed_columns:
                for column in columns:
                    if column not in self.allowed_columns:
                        return False, f"Column '{column}' is not allowed"
            
            return True, None
            
        except sqlglot.errors.ParseError as e:
            return False, f"SQL parsing error: {str(e)}"
        except Exception as e:
            logger.error(f"SQL validation error: {e}")
            return False, "SQL validation failed"

    def _extract_tables(self, parsed: exp.Expression) -> Set[str]:
        """Extract table names from parsed SQL."""
        tables = set()
        for table in parsed.find_all(exp.Table):
            table_name = table.name if table.name else str(table)
            tables.add(table_name)
        return tables

    def _extract_columns(self, parsed: exp.Expression) -> Set[str]:
        """Extract column names from parsed SQL."""
        columns = set()
        for column in parsed.find_all(exp.Column):
            column_name = column.name if column.name else str(column)
            columns.add(column_name)
        return columns

def validate_sql_for_ai(sql: str, allowed_tables: Optional[Set[str]] = None) -> tuple[bool, Optional[str]]:
    """
    Validate SQL generated by AI.
    
    Args:
        sql: The SQL query to validate
        allowed_tables: Set of allowed table names (optional)
    
    Returns:
        (is_valid, error_message)
    """
    validator = SQLValidator(allowed_tables=allowed_tables)
    return validator.validate_sql(sql)
